---
name: CI
on: [push, pull_request]

jobs:
  build:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - run: bundle exec rspec --exclude-pattern "spec/integration/**/*"

  integration:
    name: integration tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - name: Install Neovim
        run: sudo apt update && sudo apt install -y neovim
      - run: bundle exec rspec spec/integration/
